apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment
 labels:
   deployment: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
